version: '3.2'

services:
  sugarweb:
    build: '.'
    container_name: web_sugar
    restart: always
    environment:
      VIRTUAL_HOST: sugar.naturalproducts.net
      VIRTUAL_PORT: 8092
      LETSENCRYPT_HOST: sugar.naturalproducts.net
      LETSENCRYPT_EMAIL: maria.ssorokina@gmail.com
    volumes:
    - ./volume:/tmp


networks:
  default:
    external:
      name: nginx-proxy

